// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjdlpljvboksptfletdt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqZGxwbGp2Ym9rc3B0ZmxldGR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NDE1MTksImV4cCI6MjA1ODIxNzUxOX0.X3VYjp0fEpwH1AO8NV6SrU3DliKvdbPRznQyoXO-PqA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);